### ISSUE TITLE
It no longer works with aframe 1.5.0

### ISSUE THREAD

**Issue by multimedia-enpjj** [rozek/aframe-rounded-box-component#2]
I've just updated to Aframe 1.5.0 and the component no longer works;
`Uncaught (in promise) TypeError: THREE.ExtrudeBufferGeometry is not a constructor
    at NewComponent.update (aframe-rounded-box-component.ts:43:24)
    at NewComponent.initComponent (geometry.js:34:1)
    at NewComponent.updateProperties (component.js:806:1)
    at module.exports.Component (component.js:589:5)
    at new NewComponent (propertyTypes.js:218:9)
    at primitiveClass.initComponent (a-entity.js:783:3)
    at primitiveClass.updateComponent (a-mixin.js:64:9)
    at primitiveClass.updateComponents (a-mixin.js:37:3)
    at entityLoadCallback (a-entity.js:722:1)
    at emitLoaded (component.js:345:9)`

**Comment by wolffe** [comment]
Yes, THREE.ExtrudeBufferGeometry has been renamed to THREE.ExtrudeGeometry

I'd love to have this package updated.
